### ISSUE TITLE
IE11 support via babel

### ISSUE THREAD

**Issue by bdon** [GeoTIFF/geoblaze#161]
**Describe the bug**
The geoblaze build is not compatible with IE11, which is 2-3% of web traffic. Since the project is already using webpack/babel, it may be reasonable to specify older browsers as transpile/polyfill targets, but I'm not sure how to make this happen with the current .babelrc setup.

**Comment by DanielJDufour** [comment]
Hi, @bdon .  Thank you for the comment.  I absolutely agree. Would you be able to share a screenshot of the errors that you are encountering?  I'm wondering if the issue could be solved by adding specific babel plugins to the .babelrc .  Is there another webpack setup you know that could work or could refer us to?  Would you be interested in making a PR?  In either case, thank you!

**Comment by bdon** [comment]
after I run `npm run build` I am using geoblaze.web.min.js which still seems to be an es6 file, it uses the spread operator on line 21, col 21365. You can try http://bdon.org/geoblaze with ie11 on browserling.com . I thought that having preset-env defined in .babelrc would be good enough to ensure transpiling to es5, but that doesn't seem to work...

**Comment by DanielJDufour** [comment]
Okay. That's good information.  It's not ideal, but perhaps we can just add the relevant babel plugins until it works on IE 11.  https://babeljs.io/docs/en/babel-plugin-transform-spread

**Comment by bdon** [comment]
When I run `npm run build` I see that it's already using `transform-spread { "ie":"10", "safari":"7" }` in the output log, but this doesn't seem to affect the created `dist/geoblaze.web.js`, which has the spread operator (you can grep it for `(...` am I missing something?
