### ISSUE TITLE
Issue with Create-react_app -- Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by laterdude** [GeoTIFF/geoblaze#162]
Trying to utilize geoblaze on the frontend in a react app, I have the latest release of georaster concurrently installed as an independent dependency also.

Anyway, upon loading the geoblaze module into a react component, regardless of whether I use the require/import syntax, everytime I try to perform an operation like rastercalculator or load with geoblaze, I get the following error:

Uncaught ReferenceError: require is not defined
    at Object.<anonymous> (44e88b0d-451a-4137-87d5-910ea3128104:1)
and the reference is to the geoblaze.node.min script rather than the web version. I'm not sure how to get react's webpack dev server to load the minified web script in lieu of the geoblaze.node.min script. Before that there was some errors related to georaster as well, so I also tried to create the georaster directly instead of having geoblaze handle it, and passing the prepared georaster object to the geoblaze function seemed to remove those. 

Looks like maybe the package.json could be amended, just perusing npm's module docs I came across this:

"The main field is a module ID that is the primary entry point to your program. That is, if your package is named foo, and a user installs it, and then does require("foo"), then your main module’s exports object will be returned.
This should be a module ID relative to the root of your package folder.
For most modules, it makes the most sense to have a main script and often not much else.

browser§
**If your module is meant to be used client-side the browser field should be used instead of the main field. This is helpful to hint users that it might rely on primitives that aren’t available in Node.js modules. (e.g. window)**

Haven't looked into environment detection variable that might clear the issue up

Thanks -- take care

**Comment by DanielJDufour** [comment]
Hi, @laterdude .  Thanks for reporting this issue.  Unfortunately, I'm busy right now with some life stuff, so I might not be able to be of much help at the moment.  However, would you be able to share any of your code for this?  I could help me debug better with the time I have.  Thanks!

**Comment by laterdude** [comment]
It's all good, I think it's actually an underlying issue with create-react-app webpack 4, the resolver is going straight to the main entry point for some reason rather than looking first at the browser field in the package.json like it should according to the webpack 4 docs as far as I can tell since you don't utilize the module field

--> if your Webpack target is node, it looks at the module and main for entry. Otherwise, it goes to the browser, then module, then main

so it seems like something's off, but I worked around it by loading the web.min/map directly. 
Best of luck with the whole suite of geotiff products though, if you want some help with the openlayers layer component, let me know -- take it easy
