### ISSUE TITLE
max fuction has a typo that prevents using nodata value of the georaster

### ISSUE THREAD

**Issue by CLAMPE2020** [GeoTIFF/geoblaze#163]
**Describe the bug**
Line 36 of /src/max/max.module.js
const noDataValue = georaster.no_date_value;

should be (from taken from min):
const { noDataValue } = georaster;

**To Reproduce**
Use the function with a dataset where the nodata would be max.

**Expected behavior**
Output of the real max value not the nodata value

**Comment by DanielJDufour** [comment]
You're absolutely correct.  Would you like to submit a PR or should I?

**Comment by CLAMPE2020** [comment]
As I still don't know how to do that it would be nice if you would. Thanks.

**Comment by DanielJDufour** [comment]
This is now fixed. Just published a new version of GeoBlaze.
