### ISSUE TITLE
Can't use stats function

### ISSUE THREAD

**Issue by rumski20** [GeoTIFF/geoblaze#185]
**Describe the bug**
I can import geoblaze but `stats` is not available.
It doesn't seem to have an export listed here: https://github.com/GeoTIFF/geoblaze/blob/master/src/index.js

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DanielJDufour** [comment]
@rumski20 , good catch! Would you like to submit a PR?  If you don't have time, just let me know and I can do it.  Thank you!
