### ISSUE TITLE
Node worker_threads not available. 

### ISSUE THREAD

**Issue by stefanocudini** [GeoTIFF/geoblaze#193]
```javascript
const geoblaze = require('geoblaze')
const fs = require('fs');

//const file = '/MAPS/DEMS/trentino-altoadige.tif'
const file = process.argv[2];

const point = {
	"type": "Point",
	"coordinates": [
	  11.0,
	  46.0
	]
}
fs.readFile(file, async (err,data) => {
	const res = await geoblaze.identify(data, point)
	console.log(res)
});
```
run in node 16.16
return null and this error
"Node worker_threads not available. Trying to fall back to tiny-worker polyfill...                                             │o.png
null"

**Comment by stefanocudini** [comment]
The documentation is wrong!
![image](https://user-images.githubusercontent.com/47107/198874764-9949024f-a21b-40b8-b4ef-7d03f6d1b47b.png)

**Comment by stefanocudini** [comment]
nel codice vedo che può accettare soltanto georaster

con quale posso metodo aprire un file geotiff e tornare un georaster?

**Comment by DanielJDufour** [comment]
Hi, sorry for all these bugs you are finding! You can create a GeoRaster with the georaster library found here: https://github.com/geotiff/georaster

I'll look into fixing the bugs.

**Comment by acao** [comment]
fwiw, i get this warning when providing a URL to a geotiff, and it still works
