### ISSUE TITLE
Composite individual band GeoTIFFs to single GeoRaster

### ISSUE THREAD

**Issue by benboughton1** [GeoTIFF/geoblaze#195]
**Is your feature request related to a problem? Please describe.**
If I have many single bands in separate rasters can I load them into a single GeoRaster so I can do band arithmetic?

**Describe the solution you'd like**
If parse or load take in a list of GeoRasters it composites it to a multiband GeoRaster.

**Describe alternatives you've considered**
Using the geotiff.js library to create an in memory arrayBuffery and then loading that as a GeoRaster into GeoBlaze

**Additional context**

**Comment by DanielJDufour** [comment]
Hi, @benboughton1 .  That's an excellent question and one that I've wrestled with.  For your use case, are all your rasters in the same projection, same pixel size, and same bbox?  Are all your rasters geotiffs?

I'm currently solving this issue in [georaster-layer-for-leaflet](https://github.com/geotiff/georaster-layer-for-leaflet) by basically reading all the values individually, warping them to the same box+projection+resolution with [geowarp](https://github.com/danieljdufour/geowarp), and then running band arithmetic naively on them without GeoBlaze.  It's not ideal.

I would agree that adding support for multiple stacked georasters to geoblaze would be a great contribution!  Let me know if you would like to work on this :-)

**Comment by benboughton1** [comment]
Thanks for quick response. Yes they are all geotiffs, matched width, height, res etc. They are clipped Sentinel 2 or Landsat. 

I have since discovered that if I include the individual bands as datasets in the [plotty](http://santilland.github.io/plotty/module-plotty.plot.html#setExpression__anchor) library I can run an expression on that and apply colormap. This generates a PNG I can load onto my OpenLayers map. OpenLayers warps the PNG to match the projection. 

I will need to revisit this though since I will want to use some of the other geoblaze tools on the derivatives. I would like to work on it but it might be better served if I sponsored someone who knows what they are doing :). Am happy to talk further if that's an option.

**Comment by DanielJDufour** [comment]
How large are the rasters?  If all the data can be loaded into memory, I could create a simple georaster-merge library that merges the georasters together.

**Comment by benboughton1** [comment]
Easily fit in memory. Like Max 5mb per layer. Usually less than 1mb.

It sounds like a good idea. I'll reach out.

**Comment by DanielJDufour** [comment]
Hi, @benboughton1 .  Please check out this ObservableHQ notebook I just made and let me know if that helps answer your question:
https://observablehq.com/d/723dc08141af20d0

I'd agree that the code is weird at this point, so hopefully when I have more time I can rework it and make it more clean.

(also just a heads up, that I'm in the middle of a massive georaster update.  it's taking several years, so I'm not sure exactly when it'll. be done.  Just letting you know that when the next major version is released, it's possible that the code in the notebook will have to be updated.  Not sure yet)

**Comment by benboughton1** [comment]
Thankyou! This will help a lot. I will test this and reopen if I have any issues. The georaster rewrite sounds like a big task.
