### ISSUE TITLE
`rasterCalculator` with polygon clipping?

### ISSUE THREAD

**Issue by acao** [GeoTIFF/geoblaze#200]
**Is your feature request related to a problem? Please describe.**

I would love to be able to use `rasterCalculator()` to generate a custom nominal histogram that counts empty pixels.

![image](https://user-images.githubusercontent.com/1368727/236808110-14becf19-47eb-4f51-b5fa-3a133bee5fda.png)

the pixel counts here are super useful, but without knowing how many pixels were empty, I can't give an n% of pixel coverage with these land cover features

**Describe the solution you'd like**

my goal is a nominal histogram like this, just to add another key at the end, whether i need to compute and append this manually or not

```ts
{
  // this data is already present
  30: 9,
  80: 23,
  // just want to add this
  empty: 9972
}
```

I have an assumption that rasterCalculator() with geometry clipping would allow me to do this, however I'm not certain if it would handle empty pixels?

```ts
const filteredRaster = geoblaze.rasterCalculator(url, geometry, (a, b, c) => a + b === c ? 1 : 0);
```

**Describe alternatives you've considered**
I'm not sure how I would go about manually implementing a geometry clipping in `rasterCalculator` or if that's possible, because the raster calculator arguments don't provide positional information per pixel to make such a determination

If there was another way to determine the exact number of total pixels in this clipped polygon, then the provided histogram would be enough.

Perhaps there is another way to modify the source file to register band value 1000 for all empty pixels? Seems like it would add a lot of unnecessary data to the geotiff?

**Additional context**
The single band dataset I am using has these values

<img width="336" alt="Screenshot 2023-05-08 at 13 08 34" src="https://user-images.githubusercontent.com/1368727/236808803-87920bcd-a72c-4d21-989b-74bedea54f6c.png">

the full zonal stats:
<img width="300" alt="Screenshot 2023-05-08 at 13 15 34" src="https://user-images.githubusercontent.com/1368727/236810076-64a78924-0261-4383-99f2-3f930e923e06.png">

the dataset is mostly empty pixels
<img width="362" alt="Screenshot 2023-05-08 at 13 16 41" src="https://user-images.githubusercontent.com/1368727/236810285-1d164fc6-d61d-4bce-bb26-791c99800007.png">

**Comment by DanielJDufour** [comment]
Hi, @acao .  Thank you for posing such an interesting question.  We can definitely explore passing more contextual information to the rasterCalculator function.

In the meantime, I'm wondering if you might be able to achieve your desired result by turning off the `noDataValue` of your georaster.   For example:

```js
import { parse, rasterCalculator } from "geoblaze";

const georaster = await geoblaze.parse("https://example.org/image.tiff");

// turn off the noDataValue
georaster.noDataValue = undefined;

geoblaze.stats(georaster, geometry);
```

**Comment by acao** [comment]
@DanielJDufour it worked! thank you for this! 

as far as extending the raster calculator signature is concerned, I'm looking forward to that, I can brainstorm a few ideas, still getting familiar with this fantastic ecosystem.

thank you so much for this library! it's made bringing raster analysis to production for us a breeze
