### ISSUE TITLE
A multipolygon and 2 single polygons give differing results

### ISSUE THREAD

**Issue by avmey** [GeoTIFF/geoblaze#212]
**Describe the bug**
A multipolygon which has two polygons with a shared edge results in a different output than if the two polygons are fed to geoblaze separately.

**To Reproduce**
Using a valid geometry, input the following features and compare output.
`{"type":"Feature","geometry":{"type":"MultiPolygon","coordinates":
[[[[-180,-18], [-178,-18], [-178,-20], [-180,-20], [-180,-18]]],
[[[180,-20], [178,-20], [178,-18], [180,-18], [180,-20]]]]},
"properties":{}}`
&&
`{"geometry":{"type":"Polygon","coordinates":
[[[180,-20], [178,-20], [178,-18], [180,-18], [180,-20]]]}} `
`{"geometry":{"type":"Polygon","coordinates":
[[[-180,-18], [-178,-18], [-178,-20], [-180,-20], [-180,-18]]]}}`

**Expected behavior**
Output to be identical

<img width="420" alt="Screenshot 2023-07-11 at 1 27 40 PM" src="https://github.com/GeoTIFF/geoblaze/assets/22669217/013ecc94-5488-4cec-aa00-b11611e3518c">

**Comment by DanielJDufour** [comment]
I have confirmed this bug.  Will need to investigate.  My hunch is that it has to do with the antimeridian.  Thanks for catching it!

**Comment by DanielJDufour** [comment]
This should be fixed now with the most recent version of GeoBlaze
