### ISSUE TITLE
Large error when raster extent and geometry bbox don't overlap

### ISSUE THREAD

**Issue by avmey** [GeoTIFF/geoblaze#213]
**Describe the bug**
When geoblaze is fed a raster and geometry, with the raster's extent not overlapping the geometry's bbox, geoblaze outputs a range error and then a huge stack trace/ log to the console. Attempts to catch the error and continue on in the program are unsuccessful. Ensuring overlap between the raster's extent and geometry's bbox before geoblaze.sum() call is successful.

**To Reproduce**
url: a simple raster 
geom: json feature or feature collection which has a bounding box not overlapping the raster's extent
```
const raster = await geoblaze.parse(url)
const sum = await geoblaze.sum(raster, geom)
```

**Expected behavior**
A descriptive thrown error that can be caught and handled.

**Screenshots**
<img width="981" alt="Screenshot 2023-07-19 at 12 55 58 PM" src="https://github.com/GeoTIFF/geoblaze/assets/22669217/828b223e-3e2c-45a5-80c8-6a9de514a225">
<img width="976" alt="Screenshot 2023-07-19 at 12 56 07 PM" src="https://github.com/GeoTIFF/geoblaze/assets/22669217/fc239206-c9d9-4b05-92e7-7787fb285026">

**Comment by DanielJDufour** [comment]
Thanks for catching this. Could you provide the raster and geometry that are causing this?

**Comment by DanielJDufour** [comment]
@avmey

**Comment by avmey** [comment]
Rerunning the code that caused this error now runs without issue, maybe something in your recent work fixed it! All clear now.

**Comment by DanielJDufour** [comment]
Glad to hear it! Thanks for checking again :-)
